title: "Listening test: differences between violins"
testType: "similarity" # options: "similarity", "abx"
intro:
  title: "Thank you for taking part in this listening test!"
  text:
    - "The rules are simple: in each round you will have to listen to two violin recordings."
    - "You will have to judge the <b>difference</b> between the two violins being played, <b>regardless</b> of the musical interpretation."
    - "You will use a ten-value scale ranging from 'not at all different' (very similar, in other words) to 'very different'."
    - "Press X or Y to listen to a recording. Press again to pause. Use the slider to rate the difference between the violins, then move on to the next round by clicking on the arrow at the bottom right."
    - "Good luck!"
familiarization:
  title: "Familiarization:"
  text: "Here are six excerpts that are representative of the variability you will hear during this test. Compare the difference of the violins played in these six excerpts in order to create your own rating scale."
  audios:
    - label: "1"
      src: "audio/faded/A-Norimi-1.wav"
    - label: "2"
      src: "audio/faded/A-Norimi-3.wav"
    - label: "3"
      src: "audio/faded/A-Norimi-2.wav"
    - label: "4"
      src: "audio/faded/A-SMD-1.wav"
    - label: "5"
      src: "audio/faded/A-SMD-3.wav"
    - label: "6"
      src: "audio/faded/C-SMD-3.wav"
test:
  audioRoot: "audio/faded/"
  validate: true # If true, users must provide an answer before moving to the next round (ABX only)
  similarity:
    scale:
      min: 0
      max: 10
      default: 5
      labels:
        min: "Not at all different"
        max: "Very different"
    instruction: "Violins X and Y are :"
  rounds:
    - a: "A-SMD-1.wav"
      b: "A-SMD-2.wav"
    - a: "A-SMD-1.wav"
      b: "A-SMD-3.wav"
    - a: "B-SMD-1.wav"
      b: "B-SMD-2.wav"
    - a: "B-SMD-1.wav"
      b: "B-SMD-3.wav"
    - a: "C-SMD-1.wav"
      b: "C-SMD-2.wav"
    - a: "C-SMD-1.wav"
      b: "C-SMD-3.wav"
    - a: "A-SMD-3.wav"
      b: "B-SMD-3.wav"
    - a: "C-SMD-1.wav"
      b: "A-SMD-1.wav"
    - a: "A-SMD-1.wav"
      b: "A-SMD-1na.wav"
    - a: "A-SMD-2.wav"
      b: "A-SMD-2.wav"
    - a: "A-Norimi-1.wav"
      b: "A-Norimi-2.wav"
    - a: "A-Norimi-1.wav"
      b: "A-Norimi-3.wav"
    - a: "B-Norimi-1.wav"
      b: "B-Norimi-2.wav"
    - a: "B-Norimi-2.wav"
      b: "B-Norimi-3.wav"
    - a: "C-Norimi-1.wav"
      b: "C-Norimi-2.wav"
    - a: "C-Norimi-2.wav"
      b: "C-Norimi-3.wav"
    - a: "A-Norimi-1.wav"
      b: "B-Norimi-1.wav"
    - a: "C-Norimi-1.wav"
      b: "A-Norimi-1.wav"
    - a: "A-Norimi-2.wav"
      b: "A-Norimi-2na.wav"
    - a: "A-SMD-1.wav"
      b: "A-Norimi-1.wav"
conclusion:
  buttonText: "Save"
  instruction: "Click on the Save button, then OK, then write your name as the filename and save the JSON file :)"
webhookUrl: "https://hook.eu1.make.com/nis72k45hwm88gt1721hc698w36nsfaa"
contactEmail: "hugo.pauget@dalembert.upmc.fr"
