title: "ABXY Strings Comparison"
testType: "abxy"
intro:
  title: "ABXY Test"
  text:
    - "In each round, you will hear the same two reference recordings <b>A</b> and <b>B</b>."
    - "You will then hear two recordings <b>X</b> <b>Y</b>."
    - "Your task is to identify which set of strings was used for <b>X</b> (A or B) and which for <b>Y</b> (A or B)."
familiarization:
  title: "Warm-up"
  text: "Get used to set A and set B. They are going to be the same for all the tests ! "
  audios:
    - label: "Set A"
      src: "audioABXY/cut/A.wav"
    - label: "Set B"
      src: "audioABXY/cut/B.wav"
test:
  audioRoot: "audioABXY/cut/"
  validate: true
  abxy:
    instruction: "Which sets are used on X and Y ?"
  rounds:
  ## different take 1
     - a: "A.wav"
       b: "B.wav"
       x: "V1S1M1E1T2.wav" ## A
       y: "V1S2M1E1T2.wav" ## B
   ## different take 2
     - a: "A.wav"
       b: "B.wav"
       x: "V1S1M1E1T3.wav" ## A
       y: "V1S2M1E1T3.wav" ## B
  ## different microphone 1
     - a: "A.wav"
       b: "B.wav"
       x: "V1S2M2E1T1.wav" ## B
       y: "V1S1M2E1T1.wav" ## A
  ## different microphone 1
     - a: "A.wav"
       b: "B.wav"
       x: "V1S2M3E1T1.wav" ## B
       y: "V1S1M3E1T1.wav" ## A
  ## different excerpt later
     - a: "A.wav"
       b: "B.wav"
       x: "V1S1M1E2T1.wav" ## A
       y: "V1S2M1E2T1.wav" ## B
  ## different instrument 1
     - a: "A.wav"
       b: "B.wav"
       x: "V2S1M1E1T1.wav" ## A
       y: "V2S2M1E1T1.wav" ## B
  ## different instrument 2
     - a: "A.wav"
       b: "B.wav"
       x: "V3S2M1E1T1.wav" ## B
       y: "V3S1M1E1T1.wav" ## A
  ## different instrument 3
     - a: "A.wav"
       b: "B.wav"
       x: "V4S1M1E1T1.wav" ## A
       y: "V4S2M1E1T1.wav" ## B

conclusion:
  buttonText: "Save Results"
  instruction: "Thank you! Please save your results."
webhookUrl: "https://webhook.site/a9bc10a0-440b-49f1-8ba5-e16ee60353b6"
contactEmail: "thuy-an.nguyen@grenoble-inp.org"
